import 'package:latlong2/latlong.dart';

import 'continent_expedition.dart';

class AfricaExpeditionCatalog {
  AfricaExpeditionCatalog._();

  static const List<String> allAfricanCountries = <String>[
    'DZA',
    'AGO',
    'BEN',
    'BWA',
    'BFA',
    'BDI',
    'CPV',
    'CMR',
    'CAF',
    'TCD',
    'COM',
    'COD',
    'COG',
    'CIV',
    'DJI',
    'EGY',
    'GNQ',
    'ERI',
    'SWZ',
    'ETH',
    'GAB',
    'GMB',
    'GHA',
    'GIN',
    'GNB',
    'KEN',
    'LSO',
    'LBR',
    'LBY',
    'MDG',
    'MWI',
    'MLI',
    'MRT',
    'MUS',
    'MAR',
    'MOZ',
    'NAM',
    'NER',
    'NGA',
    'RWA',
    'STP',
    'SEN',
    'SYC',
    'SLE',
    'SOM',
    'ZAF',
    'SDS',
    'SDN',
    'TZA',
    'TGO',
    'TUN',
    'UGA',
    'ZMB',
    'ZWE',
  ];

  static const ContinentExpedition africa = ContinentExpedition(
    id: 'africa',
    name: 'Afrique',
    subtitle: 'Du Sahara aux îles de l’océan Indien',
    completionReward: 'Titre : Maître de l’Afrique',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'africa_01_discovery',
        order: 1,
        title: 'Découverte de l’Afrique',
        description: 'Commence avec cinq pays faciles à situer.',
        objective: 'Repérer l’Afrique du Sud, l’Égypte, l’Algérie, le Maroc et le Nigeria.',
        modeId: 'find_country',
        difficultyId: 'discovery',
        countryIds: <String>['ZAF', 'EGY', 'DZA', 'MAR', 'NGA'],
        questionCount: 5,
        questionDurationSeconds: 25,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.8,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_02_large_countries',
        order: 2,
        title: 'Les grands pays',
        description: 'Explore les plus vastes territoires africains.',
        objective: 'Identifier huit grands pays du continent.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['DZA', 'COD', 'SDN', 'LBY', 'TCD', 'NER', 'AGO', 'MLI'],
        questionCount: 8,
        questionDurationSeconds: 22,
        initialCenter: LatLng(10, 20),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_03_easy_shapes',
        order: 3,
        title: 'Pays faciles à reconnaître',
        description: 'Utilise les côtes et les formes caractéristiques.',
        objective: 'Reconnaître huit pays aux contours marqués.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['MDG', 'SOM', 'ZAF', 'SEN', 'EGY', 'MAR', 'TUN', 'GMB'],
        questionCount: 8,
        questionDurationSeconds: 20,
        initialCenter: LatLng(3, 22),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_04_neighbors',
        order: 4,
        title: 'Voisins d’Afrique de l’Ouest',
        description: 'Distingue les pays serrés autour du golfe de Guinée.',
        objective: 'Différencier dix voisins d’Afrique occidentale.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['SEN', 'MRT', 'MLI', 'GIN', 'GNB', 'GMB', 'CIV', 'GHA', 'TGO', 'BEN', 'BFA'],
        questionCount: 10,
        questionDurationSeconds: 19,
        initialCenter: LatLng(10, -3),
        initialZoom: 3.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_05_new_countries',
        order: 5,
        title: 'Cap sur l’Afrique de l’Est',
        description: 'Découvre la Corne de l’Afrique et les Grands Lacs.',
        objective: 'Apprendre dix nouveaux pays orientaux.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['ETH', 'ERI', 'DJI', 'SOM', 'KEN', 'UGA', 'RWA', 'BDI', 'TZA', 'SDS'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(4, 35),
        initialZoom: 3.1,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_06_flags',
        order: 6,
        title: 'Drapeaux principaux',
        description: 'Associe les drapeaux africains à leur pays.',
        objective: 'Retrouver dix pays grâce à leur drapeau.',
        modeId: 'find_flag',
        difficultyId: 'intermediate',
        countryIds: <String>['ZAF', 'EGY', 'MAR', 'DZA', 'NGA', 'KEN', 'ETH', 'GHA', 'SEN', 'CMR'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_07_capitals',
        order: 7,
        title: 'Capitales principales',
        description: 'Place les grandes capitales du continent.',
        objective: 'Localiser dix capitales africaines.',
        modeId: 'find_capital',
        difficultyId: 'intermediate',
        countryIds: <String>['EGY', 'MAR', 'DZA', 'TUN', 'SEN', 'GHA', 'NGA', 'ETH', 'KEN', 'AGO'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(7, 18),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_08_small_countries',
        order: 8,
        title: 'Petits pays africains',
        description: 'Zoome pour trouver les États les plus discrets.',
        objective: 'Repérer dix petits pays du continent.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>['GMB', 'SWZ', 'LSO', 'DJI', 'RWA', 'BDI', 'GNQ', 'COM', 'STP', 'CPV'],
        questionCount: 10,
        questionDurationSeconds: 22,
        initialCenter: LatLng(2, 20),
        initialZoom: 2.8,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_09_islands',
        order: 9,
        title: 'Îles et territoires',
        description: 'Pars à la recherche des îles africaines éloignées.',
        objective: 'Trouver les îles et territoires disponibles sur la carte.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>['MDG', 'MUS', 'SYC', 'COM', 'CPV', 'STP', 'IOT', 'SHN'],
        questionCount: 8,
        questionDurationSeconds: 24,
        initialCenter: LatLng(0, 28),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_10_silhouettes',
        order: 10,
        title: 'Silhouettes d’Afrique',
        description: 'Reconnais les pays uniquement grâce à leur contour.',
        objective: 'Identifier dix silhouettes africaines.',
        modeId: 'ultimate',
        difficultyId: 'hard',
        countryIds: <String>['ZAF', 'MDG', 'EGY', 'DZA', 'NGA', 'NAM', 'SOM', 'SEN', 'MOZ', 'TCD'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.7,
        rewardLabel: 'Jusqu’à 3 étoiles africaines',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'africa_11_mixed',
        order: 11,
        title: 'Épreuve mixte',
        description: 'Enchaîne pays, capitales et drapeaux.',
        objective: 'Réussir douze questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAfricanCountries,
        questionCount: 12,
        questionDurationSeconds: 17,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.6,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_12_revision',
        order: 12,
        title: 'Révision GeoBrain',
        description: 'Le GeoBrain sélectionne les pays à retravailler.',
        objective: 'Renforcer tes points faibles personnels en Afrique.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAfricanCountries,
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.6,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'africa_13_timed',
        order: 13,
        title: 'Défi chronométré',
        description: 'Réponds vite sur tout le continent.',
        objective: 'Tenir quinze questions avec seulement douze secondes.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAfricanCountries,
        questionCount: 15,
        questionDurationSeconds: 12,
        initialCenter: LatLng(5, 20),
        initialZoom: 2.5,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'africa_14_exam',
        order: 14,
        title: 'Examen africain',
        description: 'L’examen complet avant le rang Maître.',
        objective: 'Obtenir au moins une étoile sur vingt questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAfricanCountries,
        questionCount: 20,
        questionDurationSeconds: 14,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Validation de l’examen africain',
        isExam: true,
      ),
      ContinentLevel(
        id: 'africa_15_master',
        order: 15,
        title: 'Maître de l’Afrique',
        description: 'Aucun ciblage : toute la carte est ouverte.',
        objective: 'Réussir l’ultime série africaine sans aide.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAfricanCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Débloque le titre Maître de l’Afrique',
        isMaster: true,
      ),
    ],
  );
}
