import 'package:latlong2/latlong.dart';

import 'continent_expedition.dart';

class AmericasExpeditionCatalog {
  AmericasExpeditionCatalog._();

  static const List<String> allAmericanCountries = <String>[
    'CAN',
    'USA',
    'MEX',
    'BLZ',
    'GTM',
    'HND',
    'SLV',
    'NIC',
    'CRI',
    'PAN',
    'ATG',
    'BHS',
    'BRB',
    'CUB',
    'DMA',
    'DOM',
    'GRD',
    'HTI',
    'JAM',
    'KNA',
    'LCA',
    'VCT',
    'TTO',
    'ARG',
    'BOL',
    'BRA',
    'CHL',
    'COL',
    'ECU',
    'GUY',
    'PRY',
    'PER',
    'SUR',
    'URY',
    'VEN',
  ];

  static const ContinentExpedition americas = ContinentExpedition(
    id: 'americas',
    name: 'Amériques',
    subtitle: 'Du Grand Nord à la Terre de Feu',
    completionReward: 'Titre : Maître des Amériques',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'americas_01_discovery',
        order: 1,
        title: 'Découverte des Amériques',
        description: 'Commence avec cinq pays incontournables.',
        objective: 'Repérer les États-Unis, le Canada, le Mexique, le Brésil et l’Argentine.',
        modeId: 'find_country',
        difficultyId: 'discovery',
        countryIds: <String>['USA', 'CAN', 'MEX', 'BRA', 'ARG'],
        questionCount: 5,
        questionDurationSeconds: 25,
        initialCenter: LatLng(8, -78),
        initialZoom: 2.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_02_large_countries',
        order: 2,
        title: 'Les grands pays',
        description: 'Explore les plus vastes territoires américains.',
        objective: 'Identifier huit grands pays du nord au sud.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['CAN', 'USA', 'BRA', 'ARG', 'MEX', 'PER', 'COL', 'BOL'],
        questionCount: 8,
        questionDurationSeconds: 22,
        initialCenter: LatLng(8, -78),
        initialZoom: 2.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_03_easy_shapes',
        order: 3,
        title: 'Pays faciles à reconnaître',
        description: 'Utilise les côtes et les formes caractéristiques.',
        objective: 'Reconnaître huit pays aux contours marqués.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['CHL', 'CUB', 'PAN', 'URY', 'ECU', 'BRA', 'ARG', 'MEX'],
        questionCount: 8,
        questionDurationSeconds: 20,
        initialCenter: LatLng(2, -76),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_04_north_central',
        order: 4,
        title: 'Du Nord à l’Amérique centrale',
        description: 'Descends du Canada jusqu’au canal de Panama.',
        objective: 'Différencier les dix pays du nord et du centre.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['CAN', 'USA', 'MEX', 'GTM', 'BLZ', 'HND', 'SLV', 'NIC', 'CRI', 'PAN'],
        questionCount: 10,
        questionDurationSeconds: 19,
        initialCenter: LatLng(24, -95),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_05_south',
        order: 5,
        title: 'Cap sur l’Amérique du Sud',
        description: 'Découvre les Andes, l’Amazonie et le cône sud.',
        objective: 'Apprendre dix pays sud-américains.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['COL', 'VEN', 'ECU', 'PER', 'BOL', 'PRY', 'URY', 'GUY', 'SUR', 'CHL'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(-16, -61),
        initialZoom: 2.8,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_06_caribbean',
        order: 6,
        title: 'Archipel des Caraïbes',
        description: 'Zoome parmi les grandes et petites Antilles.',
        objective: 'Repérer dix États insulaires des Caraïbes.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>['CUB', 'HTI', 'DOM', 'JAM', 'BHS', 'TTO', 'BRB', 'ATG', 'DMA', 'GRD', 'LCA', 'VCT', 'KNA'],
        questionCount: 10,
        questionDurationSeconds: 22,
        initialCenter: LatLng(18, -70),
        initialZoom: 3.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_07_flags',
        order: 7,
        title: 'Drapeaux principaux',
        description: 'Associe les drapeaux américains à leur pays.',
        objective: 'Retrouver dix pays grâce à leur drapeau.',
        modeId: 'find_flag',
        difficultyId: 'intermediate',
        countryIds: <String>['USA', 'CAN', 'MEX', 'BRA', 'ARG', 'CHL', 'COL', 'CUB', 'JAM', 'PER'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_08_capitals',
        order: 8,
        title: 'Capitales principales',
        description: 'Place les grandes capitales des Amériques.',
        objective: 'Localiser dix capitales du nord au sud.',
        modeId: 'find_capital',
        difficultyId: 'intermediate',
        countryIds: <String>['USA', 'CAN', 'MEX', 'BRA', 'ARG', 'CHL', 'COL', 'CUB', 'PER', 'VEN'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_09_territories',
        order: 9,
        title: 'Territoires américains',
        description: 'Pars à la recherche des dépendances et territoires.',
        objective: 'Trouver les territoires disponibles sur la carte.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>['GRL', 'BMU', 'PRI', 'VIR', 'VGB', 'CYM', 'TCA', 'ABW', 'CUW', 'SXM', 'BLM', 'MAF', 'FLK'],
        questionCount: 12,
        questionDurationSeconds: 24,
        initialCenter: LatLng(10, -72),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_10_silhouettes',
        order: 10,
        title: 'Silhouettes des Amériques',
        description: 'Reconnais les pays uniquement grâce à leur contour.',
        objective: 'Identifier dix silhouettes américaines.',
        modeId: 'ultimate',
        difficultyId: 'hard',
        countryIds: <String>['USA', 'CAN', 'MEX', 'BRA', 'ARG', 'CHL', 'CUB', 'PAN', 'PER', 'VEN'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'Jusqu’à 3 étoiles américaines',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'americas_11_mixed',
        order: 11,
        title: 'Épreuve mixte',
        description: 'Enchaîne pays, capitales et drapeaux.',
        objective: 'Réussir douze questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAmericanCountries,
        questionCount: 12,
        questionDurationSeconds: 17,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_12_revision',
        order: 12,
        title: 'Révision GeoBrain',
        description: 'Le GeoBrain sélectionne les pays à retravailler.',
        objective: 'Renforcer tes points faibles personnels dans les Amériques.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAmericanCountries,
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'americas_13_timed',
        order: 13,
        title: 'Défi chronométré',
        description: 'Réponds vite d’un bout à l’autre des Amériques.',
        objective: 'Tenir quinze questions avec seulement douze secondes.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAmericanCountries,
        questionCount: 15,
        questionDurationSeconds: 12,
        initialCenter: LatLng(5, -78),
        initialZoom: 2.2,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'americas_14_exam',
        order: 14,
        title: 'Examen des Amériques',
        description: 'L’examen complet avant le rang Maître.',
        objective: 'Obtenir au moins une étoile sur vingt questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAmericanCountries,
        questionCount: 20,
        questionDurationSeconds: 14,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Validation de l’examen des Amériques',
        isExam: true,
      ),
      ContinentLevel(
        id: 'americas_15_master',
        order: 15,
        title: 'Maître des Amériques',
        description: 'Aucun ciblage : toute la carte est ouverte.',
        objective: 'Réussir l’ultime série américaine sans aide.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAmericanCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Débloque le titre Maître des Amériques',
        isMaster: true,
      ),
    ],
  );
}
