import 'package:latlong2/latlong.dart';

import 'continent_expedition.dart';

class AsiaExpeditionCatalog {
  AsiaExpeditionCatalog._();

  static const List<String> allAsianCountries = <String>[
    'AFG',
    'ARM',
    'AZE',
    'BHR',
    'BGD',
    'BTN',
    'BRN',
    'KHM',
    'CHN',
    'GEO',
    'IND',
    'IDN',
    'IRN',
    'IRQ',
    'ISR',
    'JPN',
    'JOR',
    'KAZ',
    'KWT',
    'KGZ',
    'LAO',
    'LBN',
    'MYS',
    'MDV',
    'MNG',
    'MMR',
    'NPL',
    'PRK',
    'OMN',
    'PAK',
    'PHL',
    'QAT',
    'RUS',
    'SAU',
    'SGP',
    'KOR',
    'LKA',
    'SYR',
    'TJK',
    'THA',
    'TLS',
    'TUR',
    'TKM',
    'ARE',
    'UZB',
    'VNM',
    'YEM',
    'TWN',
  ];

  static const ContinentExpedition asia = ContinentExpedition(
    id: 'asia',
    name: 'Asie',
    subtitle: 'Du Moyen-Orient aux archipels du Pacifique',
    completionReward: 'Titre : Maître de l’Asie',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'asia_01_discovery',
        order: 1,
        title: 'Découverte de l’Asie',
        description: 'Commence avec cinq géants très connus.',
        objective: 'Repérer la Chine, l’Inde, le Japon, l’Arabie saoudite et l’Indonésie.',
        modeId: 'find_country',
        difficultyId: 'discovery',
        countryIds: <String>['CHN', 'IND', 'JPN', 'SAU', 'IDN'],
        questionCount: 5,
        questionDurationSeconds: 25,
        initialCenter: LatLng(34, 92),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_02_large_countries',
        order: 2,
        title: 'Les grands pays',
        description: 'Explore les territoires immenses du continent.',
        objective: 'Identifier dix grands pays asiatiques.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['RUS', 'CHN', 'IND', 'KAZ', 'SAU', 'IRN', 'MNG', 'IDN', 'PAK', 'TUR'],
        questionCount: 10,
        questionDurationSeconds: 22,
        initialCenter: LatLng(40, 80),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_03_easy_shapes',
        order: 3,
        title: 'Pays faciles à reconnaître',
        description: 'Utilise les péninsules, les îles et les côtes.',
        objective: 'Reconnaître neuf pays aux formes caractéristiques.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['JPN', 'KOR', 'LKA', 'QAT', 'ARE', 'VNM', 'THA', 'PHL', 'MYS'],
        questionCount: 9,
        questionDurationSeconds: 20,
        initialCenter: LatLng(24, 105),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_04_neighbors',
        order: 4,
        title: 'Voisins du Moyen-Orient',
        description: 'Distingue les nombreux voisins de la région.',
        objective: 'Différencier douze pays proches du Moyen-Orient.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['TUR', 'SYR', 'IRQ', 'IRN', 'JOR', 'ISR', 'LBN', 'SAU', 'KWT', 'QAT', 'BHR', 'ARE', 'OMN', 'YEM'],
        questionCount: 12,
        questionDurationSeconds: 19,
        initialCenter: LatLng(28, 45),
        initialZoom: 3.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_05_new_countries',
        order: 5,
        title: 'Nouvelles routes d’Asie',
        description: 'Découvre l’Asie centrale et du Sud-Est.',
        objective: 'Apprendre dix nouveaux pays au centre et au sud-est.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['KAZ', 'UZB', 'TKM', 'KGZ', 'TJK', 'KHM', 'LAO', 'MMR', 'BRN', 'TLS'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(30, 82),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_06_flags',
        order: 6,
        title: 'Drapeaux principaux',
        description: 'Associe les grands drapeaux asiatiques à leur pays.',
        objective: 'Retrouver dix pays grâce à leur drapeau.',
        modeId: 'find_flag',
        difficultyId: 'intermediate',
        countryIds: <String>['CHN', 'IND', 'JPN', 'KOR', 'IDN', 'THA', 'VNM', 'TUR', 'SAU', 'ISR'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(30, 85),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_07_capitals',
        order: 7,
        title: 'Capitales principales',
        description: 'Place les capitales les plus connues d’Asie.',
        objective: 'Localiser dix grandes capitales asiatiques.',
        modeId: 'find_capital',
        difficultyId: 'intermediate',
        countryIds: <String>['CHN', 'IND', 'JPN', 'KOR', 'THA', 'VNM', 'TUR', 'IRN', 'SAU', 'IDN'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(31, 85),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_08_small_countries',
        order: 8,
        title: 'Petits pays asiatiques',
        description: 'Zoome pour trouver les États les plus discrets.',
        objective: 'Repérer neuf petits pays du continent.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>['SGP', 'BHR', 'QAT', 'KWT', 'LBN', 'BRN', 'MDV', 'BTN', 'TLS'],
        questionCount: 9,
        questionDurationSeconds: 22,
        initialCenter: LatLng(20, 80),
        initialZoom: 2.6,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_09_islands_territories',
        order: 9,
        title: 'Îles et régions spéciales',
        description: 'Pars à la recherche des petites entités asiatiques.',
        objective: 'Trouver les îles et régions spéciales disponibles.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>['HKG', 'MAC', 'IOT', 'MDV', 'SGP', 'BRN', 'TLS', 'LKA'],
        questionCount: 8,
        questionDurationSeconds: 24,
        initialCenter: LatLng(15, 90),
        initialZoom: 2.5,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_10_silhouettes',
        order: 10,
        title: 'Silhouettes d’Asie',
        description: 'Reconnais les pays uniquement grâce à leur contour.',
        objective: 'Identifier dix silhouettes asiatiques.',
        modeId: 'ultimate',
        difficultyId: 'hard',
        countryIds: <String>['CHN', 'IND', 'JPN', 'SAU', 'KOR', 'VNM', 'THA', 'LKA', 'PHL', 'IDN'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(30, 90),
        initialZoom: 2.5,
        rewardLabel: 'Jusqu’à 3 étoiles asiatiques',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'asia_11_mixed',
        order: 11,
        title: 'Épreuve mixte',
        description: 'Enchaîne pays, capitales et drapeaux.',
        objective: 'Réussir douze questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAsianCountries,
        questionCount: 12,
        questionDurationSeconds: 17,
        initialCenter: LatLng(32, 88),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_12_revision',
        order: 12,
        title: 'Révision GeoBrain',
        description: 'Le GeoBrain sélectionne les pays à retravailler.',
        objective: 'Renforcer tes points faibles personnels en Asie.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAsianCountries,
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(32, 88),
        initialZoom: 2.4,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'asia_13_timed',
        order: 13,
        title: 'Défi chronométré',
        description: 'Réponds vite sur le plus vaste continent.',
        objective: 'Tenir quinze questions avec seulement douze secondes.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allAsianCountries,
        questionCount: 15,
        questionDurationSeconds: 12,
        initialCenter: LatLng(32, 88),
        initialZoom: 2.3,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'asia_14_exam',
        order: 14,
        title: 'Examen asiatique',
        description: 'L’examen complet avant le rang Maître.',
        objective: 'Obtenir au moins une étoile sur vingt questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAsianCountries,
        questionCount: 20,
        questionDurationSeconds: 14,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Validation de l’examen asiatique',
        isExam: true,
      ),
      ContinentLevel(
        id: 'asia_15_master',
        order: 15,
        title: 'Maître de l’Asie',
        description: 'Aucun ciblage : toute la carte est ouverte.',
        objective: 'Réussir l’ultime série asiatique sans aide.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allAsianCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Débloque le titre Maître de l’Asie',
        isMaster: true,
      ),
    ],
  );
}
