import 'package:latlong2/latlong.dart';

import 'continent_expedition.dart';

class EuropeExpeditionCatalog {
  EuropeExpeditionCatalog._();

  static const List<String> allEuropeanCountries = <String>[
    'ALB',
    'AND',
    'AUT',
    'BEL',
    'BGR',
    'BIH',
    'BLR',
    'CHE',
    'CYP',
    'CZE',
    'DEU',
    'DNK',
    'ESP',
    'EST',
    'FIN',
    'FRA',
    'GBR',
    'GRC',
    'HRV',
    'HUN',
    'IRL',
    'ISL',
    'ITA',
    'KOS',
    'LIE',
    'LTU',
    'LUX',
    'LVA',
    'MCO',
    'MDA',
    'MKD',
    'MLT',
    'MNE',
    'NLD',
    'NOR',
    'POL',
    'PRT',
    'ROU',
    'RUS',
    'SMR',
    'SRB',
    'SVK',
    'SVN',
    'SWE',
    'UKR',
    'VAT',
  ];

  static const ContinentExpedition europe = ContinentExpedition(
    id: 'europe',
    name: 'Europe',
    subtitle: 'Du premier repérage au titre de Maître de l’Europe',
    completionReward: 'Titre : Maître de l’Europe',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'europe_01_discovery',
        order: 1,
        title: 'Découverte de l’Europe',
        description: 'Commence avec cinq pays très connus.',
        objective: 'Repérer la France, l’Espagne, le Portugal, l’Italie et l’Allemagne.',
        modeId: 'find_country',
        difficultyId: 'discovery',
        countryIds: <String>['FRA', 'ESP', 'PRT', 'ITA', 'DEU'],
        questionCount: 5,
        questionDurationSeconds: 25,
        initialCenter: LatLng(47, 6),
        initialZoom: 3.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_02_large_countries',
        order: 2,
        title: 'Les grands pays',
        description: 'Identifie les grands territoires européens.',
        objective: 'Obtenir au moins une étoile sur huit questions.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['FRA', 'ESP', 'DEU', 'ITA', 'GBR', 'UKR', 'POL', 'SWE'],
        questionCount: 8,
        questionDurationSeconds: 22,
        initialCenter: LatLng(52, 12),
        initialZoom: 3.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_03_easy_shapes',
        order: 3,
        title: 'Pays faciles à reconnaître',
        description: 'Îles, péninsules et formes caractéristiques.',
        objective: 'Reconnaître huit pays aux formes marquées.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['IRL', 'ISL', 'GRC', 'NOR', 'DNK', 'ITA', 'PRT', 'GBR'],
        questionCount: 8,
        questionDurationSeconds: 20,
        initialCenter: LatLng(53, 5),
        initialZoom: 2.9,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_04_neighbors',
        order: 4,
        title: 'Pays voisins',
        description: 'Distingue les pays serrés au cœur de l’Europe.',
        objective: 'Différencier les voisins d’Europe centrale.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['BEL', 'NLD', 'LUX', 'DEU', 'CHE', 'AUT', 'CZE', 'SVK', 'HUN', 'SVN'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(49, 11),
        initialZoom: 3.5,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_05_new_countries',
        order: 5,
        title: 'Nouveaux pays',
        description: 'Pars vers les Balkans et l’Europe orientale.',
        objective: 'Découvrir dix nouveaux pays européens.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['ROU', 'BGR', 'SRB', 'BIH', 'MNE', 'ALB', 'MKD', 'MDA', 'LTU', 'LVA', 'EST'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(46, 23),
        initialZoom: 3.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_06_flags',
        order: 6,
        title: 'Drapeaux principaux',
        description: 'Associe les grands drapeaux à leur pays.',
        objective: 'Retrouver dix pays grâce à leur drapeau.',
        modeId: 'find_flag',
        difficultyId: 'intermediate',
        countryIds: <String>['FRA', 'DEU', 'ITA', 'ESP', 'GBR', 'PRT', 'NLD', 'BEL', 'CHE', 'AUT'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(50, 8),
        initialZoom: 3.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_07_capitals',
        order: 7,
        title: 'Capitales principales',
        description: 'Place les capitales les plus connues.',
        objective: 'Localiser dix capitales européennes.',
        modeId: 'find_capital',
        difficultyId: 'intermediate',
        countryIds: <String>['FRA', 'GBR', 'DEU', 'ITA', 'ESP', 'PRT', 'NLD', 'BEL', 'AUT', 'CZE', 'POL', 'GRC'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(50, 10),
        initialZoom: 2.9,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_08_small_countries',
        order: 8,
        title: 'Petits pays',
        description: 'Zoome pour trouver les micro-États européens.',
        objective: 'Repérer les huit plus petits pays.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>['LUX', 'AND', 'MCO', 'LIE', 'SMR', 'VAT', 'MLT', 'CYP'],
        questionCount: 8,
        questionDurationSeconds: 22,
        initialCenter: LatLng(45, 9),
        initialZoom: 3.2,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_09_territories',
        order: 9,
        title: 'Territoires européens',
        description: 'Découvre les dépendances et territoires particuliers.',
        objective: 'Trouver les territoires disponibles sur la carte.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>['FRO', 'GIB', 'IMN', 'JEY', 'GGY', 'ALD'],
        questionCount: 6,
        questionDurationSeconds: 24,
        initialCenter: LatLng(55, 1),
        initialZoom: 2.6,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_10_silhouettes',
        order: 10,
        title: 'Silhouettes d’Europe',
        description: 'Reconnais les pays uniquement grâce à leur contour.',
        objective: 'Identifier les silhouettes européennes.',
        modeId: 'ultimate',
        difficultyId: 'hard',
        countryIds: <String>['FRA', 'ESP', 'PRT', 'ITA', 'DEU', 'GBR', 'IRL', 'ISL', 'GRC', 'NOR'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(50, 10),
        initialZoom: 3.0,
        rewardLabel: 'Jusqu’à 3 étoiles européennes',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'europe_11_mixed',
        order: 11,
        title: 'Épreuve mixte',
        description: 'Enchaîne pays, capitales et drapeaux.',
        objective: 'Réussir douze questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allEuropeanCountries,
        questionCount: 12,
        questionDurationSeconds: 17,
        initialCenter: LatLng(52, 12),
        initialZoom: 2.7,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_12_revision',
        order: 12,
        title: 'Révision GeoBrain',
        description: 'Le GeoBrain sélectionne les pays à retravailler.',
        objective: 'Renforcer tes points faibles personnels.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allEuropeanCountries,
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(52, 12),
        initialZoom: 2.7,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'europe_13_timed',
        order: 13,
        title: 'Défi chronométré',
        description: 'Réponds vite sur toute l’Europe.',
        objective: 'Tenir quinze questions avec seulement douze secondes.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allEuropeanCountries,
        questionCount: 15,
        questionDurationSeconds: 12,
        initialCenter: LatLng(52, 12),
        initialZoom: 2.6,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'europe_14_exam',
        order: 14,
        title: 'Examen européen',
        description: 'L’examen complet avant le rang Maître.',
        objective: 'Obtenir au moins une étoile sur vingt questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allEuropeanCountries,
        questionCount: 20,
        questionDurationSeconds: 14,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Validation de l’examen européen',
        isExam: true,
      ),
      ContinentLevel(
        id: 'europe_15_master',
        order: 15,
        title: 'Maître de l’Europe',
        description: 'Aucun ciblage : toute la carte est ouverte.',
        objective: 'Réussir l’ultime série européenne sans aide.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allEuropeanCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Débloque le titre Maître de l’Europe',
        isMaster: true,
      ),
    ],
  );
}
