import 'package:latlong2/latlong.dart';

import 'continent_expedition.dart';

class OceaniaExpeditionCatalog {
  OceaniaExpeditionCatalog._();

  static const List<String> allOceanianCountries = <String>[
    'AUS',
    'NZL',
    'PNG',
    'FJI',
    'SLB',
    'VUT',
    'WSM',
    'TON',
    'TUV',
    'KIR',
    'NRU',
    'PLW',
    'FSM',
    'MHL',
  ];

  static const ContinentExpedition oceania = ContinentExpedition(
    id: 'oceania',
    name: 'Océanie',
    subtitle: 'De l’Australie aux archipels du Pacifique',
    completionReward: 'Titre : Maître de l’Océanie',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'oceania_01_discovery',
        order: 1,
        title: 'Découverte de l’Océanie',
        description: 'Commence avec cinq grands repères du Pacifique.',
        objective: 'Repérer l’Australie, la Nouvelle-Zélande, '
            'la Papouasie-Nouvelle-Guinée, les Fidji et les Salomon.',
        modeId: 'find_country',
        difficultyId: 'discovery',
        countryIds: <String>['AUS', 'NZL', 'PNG', 'FJI', 'SLB'],
        questionCount: 5,
        questionDurationSeconds: 25,
        initialCenter: LatLng(-18, 155),
        initialZoom: 2.5,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_02_large_landmarks',
        order: 2,
        title: 'Grands repères du Pacifique',
        description: 'Observe les terres les plus visibles de la région.',
        objective: 'Identifier six grands repères océaniens.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['AUS', 'PNG', 'NZL', 'NCL', 'FJI', 'SLB'],
        questionCount: 6,
        questionDurationSeconds: 22,
        initialCenter: LatLng(-18, 155),
        initialZoom: 2.5,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_03_melanesia',
        order: 3,
        title: 'Cap sur la Mélanésie',
        description: 'Explore les îles situées au nord-est de l’Australie.',
        objective: 'Différencier les cinq territoires de Mélanésie.',
        modeId: 'find_country',
        difficultyId: 'easy',
        countryIds: <String>['PNG', 'FJI', 'SLB', 'VUT', 'NCL'],
        questionCount: 5,
        questionDurationSeconds: 20,
        initialCenter: LatLng(-16, 162),
        initialZoom: 3.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_04_micronesia',
        order: 4,
        title: 'Les îles de Micronésie',
        description: 'Zoome sur les petits États du Pacifique nord.',
        objective: 'Repérer sept pays et territoires micronésiens.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['FSM', 'MHL', 'PLW', 'NRU', 'KIR', 'GUM', 'MNP'],
        questionCount: 7,
        questionDurationSeconds: 20,
        initialCenter: LatLng(8, 150),
        initialZoom: 3.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_05_polynesia',
        order: 5,
        title: 'Voyage en Polynésie',
        description: 'Traverse l’immense triangle polynésien.',
        objective: 'Retrouver neuf pays et territoires de Polynésie.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>['WSM', 'TON', 'TUV', 'COK', 'NIU', 'PYF', 'ASM', 'WLF', 'NZL'],
        questionCount: 9,
        questionDurationSeconds: 20,
        initialCenter: LatLng(-15, -160),
        initialZoom: 2.9,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_06_flags',
        order: 6,
        title: 'Drapeaux principaux',
        description: 'Associe les drapeaux du Pacifique à leur pays.',
        objective: 'Retrouver dix pays grâce à leur drapeau.',
        modeId: 'find_flag',
        difficultyId: 'intermediate',
        countryIds: <String>['AUS', 'NZL', 'PNG', 'FJI', 'WSM', 'TON', 'VUT', 'KIR', 'PLW', 'MHL'],
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_07_capitals',
        order: 7,
        title: 'Capitales principales',
        description: 'Place les principales capitales d’Océanie.',
        objective: 'Localiser dix capitales du Pacifique.',
        modeId: 'find_capital',
        difficultyId: 'intermediate',
        countryIds: <String>['AUS', 'NZL', 'PNG', 'FJI', 'WSM', 'TON', 'VUT', 'SLB', 'FSM', 'MHL'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_08_microstates',
        order: 8,
        title: 'Micro-États du Pacifique',
        description: 'Les plus petits pays demandent un zoom précis.',
        objective: 'Différencier huit petits États insulaires.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>['NRU', 'TUV', 'KIR', 'PLW', 'FSM', 'MHL', 'TON', 'WSM'],
        questionCount: 8,
        questionDurationSeconds: 22,
        initialCenter: LatLng(0, 170),
        initialZoom: 2.8,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_09_territories',
        order: 9,
        title: 'Territoires océaniens',
        description: 'Pars à la recherche des territoires les plus isolés.',
        objective: 'Trouver dix territoires disponibles sur la carte.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>[
          'NCL',
          'PYF',
          'GUM',
          'ASM',
          'MNP',
          'COK',
          'NIU',
          'WLF',
          'NFK',
          'PCN',
          'UMI',
        ],
        questionCount: 10,
        questionDurationSeconds: 24,
        initialCenter: LatLng(-5, 170),
        initialZoom: 2.4,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_10_silhouettes',
        order: 10,
        title: 'Silhouettes d’Océanie',
        description: 'Reconnais les pays uniquement grâce à leur contour.',
        objective: 'Identifier dix silhouettes océaniennes.',
        modeId: 'ultimate',
        difficultyId: 'hard',
        countryIds: <String>['AUS', 'NZL', 'PNG', 'FJI', 'SLB', 'VUT', 'NCL', 'WSM', 'TON', 'KIR'],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'Jusqu’à 3 étoiles océaniennes',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'oceania_11_mixed',
        order: 11,
        title: 'Épreuve mixte',
        description: 'Enchaîne pays, capitales et drapeaux.',
        objective: 'Réussir douze questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allOceanianCountries,
        questionCount: 12,
        questionDurationSeconds: 17,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_12_revision',
        order: 12,
        title: 'Révision GeoBrain',
        description: 'Le GeoBrain sélectionne les pays à retravailler.',
        objective: 'Renforcer tes points faibles personnels en Océanie.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allOceanianCountries,
        questionCount: 10,
        questionDurationSeconds: 18,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'oceania_13_timed',
        order: 13,
        title: 'Défi chronométré',
        description: 'Réponds vite au milieu des îles du Pacifique.',
        objective: 'Tenir quinze questions avec seulement douze secondes.',
        modeId: 'mixed',
        difficultyId: 'hard',
        countryIds: allOceanianCountries,
        questionCount: 15,
        questionDurationSeconds: 12,
        initialCenter: LatLng(-8, 165),
        initialZoom: 2.3,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'oceania_14_exam',
        order: 14,
        title: 'Examen océanien',
        description: 'L’examen complet avant le rang Maître.',
        objective: 'Obtenir au moins une étoile sur vingt questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allOceanianCountries,
        questionCount: 20,
        questionDurationSeconds: 14,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Validation de l’examen océanien',
        isExam: true,
      ),
      ContinentLevel(
        id: 'oceania_15_master',
        order: 15,
        title: 'Maître de l’Océanie',
        description: 'Aucun ciblage : toute la carte est ouverte.',
        objective: 'Réussir l’ultime série océanienne sans aide.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allOceanianCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.2,
        rewardLabel: 'Débloque le titre Maître de l’Océanie',
        isMaster: true,
      ),
    ],
  );
}
