import 'package:latlong2/latlong.dart';

import 'africa_expedition.dart';
import 'americas_expedition.dart';
import 'asia_expedition.dart';
import 'continent_expedition.dart';
import 'europe_expedition.dart';
import 'oceania_expedition.dart';

class WorldExpeditionCatalog {
  WorldExpeditionCatalog._();

  static const List<String> allWorldCountries = <String>[
    ...EuropeExpeditionCatalog.allEuropeanCountries,
    ...AfricaExpeditionCatalog.allAfricanCountries,
    ...AsiaExpeditionCatalog.allAsianCountries,
    ...AmericasExpeditionCatalog.allAmericanCountries,
    ...OceaniaExpeditionCatalog.allOceanianCountries,
  ];

  static const ContinentExpedition world = ContinentExpedition(
    id: 'world',
    name: 'Monde',
    subtitle: 'L’ultime voyage autour de la planète',
    completionReward: 'Titre : Maître cartographe',
    levels: <ContinentLevel>[
      ContinentLevel(
        id: 'world_01_landmarks',
        order: 1,
        title: 'Grands repères du monde',
        description: 'Retrouve les pays emblématiques des cinq continents.',
        objective: 'Localiser dix grands repères mondiaux.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>[
          'FRA',
          'EGY',
          'ZAF',
          'USA',
          'BRA',
          'CHN',
          'IND',
          'JPN',
          'AUS',
          'NZL',
        ],
        questionCount: 10,
        questionDurationSeconds: 20,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_02_giants',
        order: 2,
        title: 'Les géants de la planète',
        description: 'Les plus vastes pays sont dispersés sur le globe.',
        objective: 'Identifier douze grands territoires mondiaux.',
        modeId: 'find_country',
        difficultyId: 'intermediate',
        countryIds: <String>[
          'RUS',
          'CAN',
          'USA',
          'CHN',
          'BRA',
          'AUS',
          'IND',
          'ARG',
          'KAZ',
          'DZA',
          'COD',
          'SAU',
        ],
        questionCount: 12,
        questionDurationSeconds: 18,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_03_shapes',
        order: 3,
        title: 'Formes du bout du monde',
        description: 'Utilise les côtes et les silhouettes caractéristiques.',
        objective: 'Distinguer douze pays aux formes marquées.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>[
          'CHL',
          'VNM',
          'GMB',
          'ITA',
          'NOR',
          'HRV',
          'PAN',
          'CUB',
          'JPN',
          'LKA',
          'NZL',
          'MDG',
        ],
        questionCount: 12,
        questionDurationSeconds: 18,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_04_islands',
        order: 4,
        title: 'Îles autour du monde',
        description: 'Traverse les océans d’un archipel à l’autre.',
        objective: 'Retrouver quinze États insulaires.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>[
          'ISL',
          'IRL',
          'GBR',
          'CUB',
          'JAM',
          'MDG',
          'MUS',
          'LKA',
          'MDV',
          'JPN',
          'PHL',
          'IDN',
          'PNG',
          'FJI',
          'NZL',
        ],
        questionCount: 15,
        questionDurationSeconds: 18,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_05_neighbors',
        order: 5,
        title: 'Frontières du monde',
        description: 'Les pays voisins peuvent facilement se confondre.',
        objective: 'Différencier vingt pays proches les uns des autres.',
        modeId: 'find_country',
        difficultyId: 'hard',
        countryIds: <String>[
          'ESP',
          'PRT',
          'FRA',
          'DEU',
          'USA',
          'CAN',
          'BRA',
          'ARG',
          'CHN',
          'MNG',
          'IND',
          'PAK',
          'KEN',
          'TZA',
          'ZAF',
          'NAM',
          'THA',
          'KHM',
          'COL',
          'VEN',
        ],
        questionCount: 15,
        questionDurationSeconds: 17,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_06_flags',
        order: 6,
        title: 'Drapeaux du monde',
        description: 'Les couleurs nationales se mélangent entre continents.',
        objective: 'Associer vingt drapeaux à leur pays.',
        modeId: 'find_flag',
        difficultyId: 'hard',
        countryIds: <String>[
          'FRA',
          'DEU',
          'ITA',
          'NGA',
          'ZAF',
          'EGY',
          'USA',
          'CAN',
          'BRA',
          'ARG',
          'CHN',
          'JPN',
          'IND',
          'KOR',
          'AUS',
          'NZL',
          'FJI',
          'PNG',
          'MEX',
          'TUR',
        ],
        questionCount: 20,
        questionDurationSeconds: 16,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_07_capitals',
        order: 7,
        title: 'Capitales du monde',
        description: 'Place les grandes capitales sans indice continental.',
        objective: 'Localiser vingt capitales internationales.',
        modeId: 'find_capital',
        difficultyId: 'hard',
        countryIds: <String>[
          'FRA',
          'GBR',
          'ESP',
          'EGY',
          'KEN',
          'ZAF',
          'USA',
          'CAN',
          'BRA',
          'ARG',
          'CHN',
          'JPN',
          'IND',
          'THA',
          'AUS',
          'NZL',
          'FJI',
          'MEX',
          'TUR',
          'RUS',
        ],
        questionCount: 20,
        questionDurationSeconds: 18,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_08_microstates',
        order: 8,
        title: 'Micro-États de la planète',
        description: 'Les plus petits pays demandent beaucoup de précision.',
        objective: 'Repérer vingt petits États sur toute la carte.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>[
          'AND',
          'LIE',
          'LUX',
          'MCO',
          'SMR',
          'VAT',
          'MLT',
          'CPV',
          'COM',
          'STP',
          'SYC',
          'BHR',
          'SGP',
          'MDV',
          'BRN',
          'NRU',
          'TUV',
          'TON',
          'WSM',
          'PLW',
        ],
        questionCount: 15,
        questionDurationSeconds: 22,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_09_polar_territories',
        order: 9,
        title: 'Territoires polaires et isolés',
        description: 'Explore l’Antarctique, l’Arctique et les îles lointaines.',
        objective: 'Trouver quinze territoires aux confins du monde.',
        modeId: 'find_country',
        difficultyId: 'expert',
        countryIds: <String>[
          'ATA',
          'GRL',
          'ATF',
          'SGS',
          'HMD',
          'FLK',
          'FRO',
          'SPM',
          'SHN',
          'IOT',
          'NFK',
          'PCN',
          'UMI',
          'NCL',
          'PYF',
        ],
        questionCount: 15,
        questionDurationSeconds: 24,
        initialCenter: LatLng(-25, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_10_silhouettes',
        order: 10,
        title: 'Silhouettes mondiales',
        description: 'Reconnais les pays sans carte ni nom.',
        objective: 'Identifier vingt silhouettes internationales.',
        modeId: 'ultimate',
        difficultyId: 'expert',
        countryIds: <String>[
          'FRA',
          'ITA',
          'NOR',
          'GBR',
          'ZAF',
          'MDG',
          'SEN',
          'USA',
          'BRA',
          'ARG',
          'CHL',
          'CUB',
          'CHN',
          'IND',
          'JPN',
          'VNM',
          'AUS',
          'NZL',
          'PNG',
          'FJI',
        ],
        questionCount: 20,
        questionDurationSeconds: 18,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'Jusqu’à 3 étoiles mondiales',
        isSilhouette: true,
      ),
      ContinentLevel(
        id: 'world_11_mixed',
        order: 11,
        title: 'Tour du monde mixte',
        description: 'Pays, capitales et drapeaux s’enchaînent sans ciblage.',
        objective: 'Réussir vingt questions de types différents.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allWorldCountries,
        questionCount: 20,
        questionDurationSeconds: 15,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'XP de la partie + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_12_revision',
        order: 12,
        title: 'Révision GeoBrain mondiale',
        description: 'Le GeoBrain rassemble tes faiblesses de toute la planète.',
        objective: 'Renforcer les pays encore mal maîtrisés.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allWorldCountries,
        questionCount: 15,
        questionDurationSeconds: 16,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'Révision personnalisée + jusqu’à 3 étoiles',
        useGeoBrain: true,
      ),
      ContinentLevel(
        id: 'world_13_timed',
        order: 13,
        title: 'Défi mondial chronométré',
        description: 'La planète entière, sans ciblage et contre la montre.',
        objective: 'Tenir vingt-cinq questions avec douze secondes.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allWorldCountries,
        questionCount: 25,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'Bonus de score temporel + jusqu’à 3 étoiles',
      ),
      ContinentLevel(
        id: 'world_14_exam',
        order: 14,
        title: 'Examen mondial',
        description: 'L’examen final couvre tous les continents.',
        objective: 'Obtenir au moins une étoile sur trente questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allWorldCountries,
        questionCount: 30,
        questionDurationSeconds: 12,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'Validation de l’examen mondial',
        isExam: true,
      ),
      ContinentLevel(
        id: 'world_15_master',
        order: 15,
        title: 'Maître cartographe',
        description: 'Aucun ciblage, aucune aide et toute la planète ouverte.',
        objective: 'Réussir l’ultime série de quarante questions.',
        modeId: 'mixed',
        difficultyId: 'expert',
        countryIds: allWorldCountries,
        questionCount: 40,
        questionDurationSeconds: 10,
        initialCenter: LatLng(20, 0),
        initialZoom: 2.0,
        rewardLabel: 'Débloque le titre Maître cartographe',
        isMaster: true,
      ),
    ],
  );
}
